title: Kowshika N
logo: "/images/logo.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a reliable, fast learning and dedicated freelancer with a quick grasping capability. <br>
  I deliver each task with the highest quality in a short time using latest automated tools and methods. 
  <br><br>
  <a href="https://www.linkedin.com/in/kowshika-n/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/kowshika-n/">View My GitHub Profile</a> 
  <br>
  <a href="https://www.upwork.com/o/profiles/users/~01839791ddb1ede3fa/">View My Upwork Profile</a> 
  <br><br>  <br><br>
 
 
theme: jekyll-theme-minimal
google_analytics: UA-171309836-1
