title: Kowshika N
logo: "/images/logo.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Kowshika is a reliable, fast learning and dedicated freelancer with a quick grasping capability. She delivers each task with the highest quality in a short time using latest automated tools and methods. 
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/kowshika-n/">View My LinkedIn Profile</a> 
  <a href="https://github.com/kowshika-n/">View My GitHub Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-171309836-1
