title: Kowshika N
logo: "/images/logo.png?raw=true"
preview: "/images/preview.png"
header-img: "/images/preview.png"
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a reliable, fast learning and dedicated freelancer with more than 5 yrs of professional experience.<br>
  I deliver each task with the highest quality in a short time using latest automated tools and technologies. With 100% Job Success Score and experience working with worldwide clients, I render my services to you.
  <br><br>
  <a href="https://www.upwork.com/o/profiles/users/~01839791ddb1ede3fa/">Upwork</a>&nbsp;&nbsp;&nbsp;<a href="https://www.fiverr.com/kowshikanagaraj/">Fiverr</a><br>
  <a href="https://www.linkedin.com/in/kowshika-n/">LinkedIn</a>&nbsp;&nbsp;<a href="https://github.com/kowshika-n/">GitHub</a> 
  <br>

pagedescription:
    is one of the many services that I offer to my clients. I enjoy solving problems. Here you can find out what I can do, to help solve your problems.
  <br><br>
  <a href="https://www.upwork.com/o/profiles/users/~01839791ddb1ede3fa/">Upwork</a>&nbsp;&nbsp;&nbsp;<a href="https://www.fiverr.com/kowshikanagaraj/">Fiverr</a><br>
  <a href="https://www.linkedin.com/in/kowshika-n/">LinkedIn</a>&nbsp;&nbsp;<a href="https://github.com/kowshika-n/">GitHub</a> 
  <br>

github_repo: "https://github.com/kowshika-n/kowshika-n.github.io.git" # you code repository

theme: jekyll-theme-minimal
google_analytics: UA-171309836-1

chrome-tab-theme-color: "#000000"
service-worker: true
